version: '3'
services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 088fc01375fe2b689db8a872912392c6
      POSTGRES_DB: test_db
    ports:
      - "15432:5432"
    volumes:
    - ./.postgres_init/:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d test_db" ]
      timeout: 15s
      interval: 5s
      retries: 10

  redis:
    image: redis:5.0.9
    command: [
        "--requirepass",
        "34b2d02037a461b42754abfedbf4b7a0"
    ]
    restart: always
    ports:
      - "16379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "ping" ]
      timeout: 3s
      interval: 1s
      retries: 30
